---
title: "incident_infection_final"
output: pdf_document
date: "2024-02-18"
author: "Qiyu Wang"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load library}
library(tidyverse)
library(haven)
library(ggplot2)
```

## load data and preprocessing
```{r load data}
all.visit.border <- 
  read_dta(
    "~/Documents/malaria_phip/PRISM_data/PRISM Border Cohort Study all visits database_FINAL.dta"
  )
dow.data <-
  read_dta("~/Documents/malaria_phip/PRISM_data/PRISM Border Cohort Study individual level database_FINAL.dta")
pbc_cluster <- 
  read.table(
  "~/Documents/malaria_phip/PRISM_data/pbc_final_selectedClustersInfo_2024_02_22.tab.txt",
  sep="\t", header=TRUE)
```

```{r genotyping processing}
# get name and date
df.pbc <- pbc_cluster %>% 
  filter(substr(s_Sample,1,1) != "C") %>%
  tidyr::extract(
  s_Sample,
  into = c("date", "cohortid"),
  regex = "([[:alnum:]-]{10})-ID_([[:alnum:]]{1,3})") %>%
  mutate(
    date = lubridate::ymd(date),
    cohortid = as.numeric(cohortid)
  ) %>%
  filter(date <= '2023-01-31', c_RepCnt == 2) %>%
  arrange(cohortid)


# remove false positive
df.pbc <- df.pbc %>% left_join(all.visit.border %>% select(cohortid, date, qpcr), 
                               by = join_by(date, cohortid)) %>%
  filter(qpcr > 0) %>% select(!qpcr)
```

```{r all visit processing}
# filter out useless variable
df.allvisit <- all.visit.border %>% filter(Phase != 0) %>%
  select(cohortid, enrolldate, date, malariacat, qpcr, parasitedensity, malaria, travelout, gender, BSdich, qPCRdich) 
# add follow-up time, malaria times, and travel times up to 2023-01-31
# merge with dow
df.allvisit <- df.allvisit %>% left_join(dow.data%>%select(cohortid, dow), by = "cohortid")
df.allvisit <- df.allvisit %>%
  group_by(cohortid) %>%
  mutate(followup = ifelse(!is.na(dow) & dow < '2023-01-31', as.numeric(round(difftime(dow, min(enrolldate))))+days(1),as.numeric(round(difftime('2023-02-01', min(enrolldate)))))) %>%
  filter(followup > 0) %>%
  filter(date <= '2023-01-31') %>%
  mutate(anymalaria = sum(as.integer(malaria!=1)),
         anytravelout = sum(as.integer(travelout==1), na.rm = TRUE),
         gender = ifelse(gender==1, "Male", "Female")) %>% ungroup()
# factorize
df.allvisit$gender <- factor(df.allvisit$gender)
df.allvisit$gender <- relevel(df.allvisit$gender, ref = 'Male')
# merge to find failure date
df.allvisit <- df.allvisit %>% left_join(df.pbc %>% select(cohortid, date, h_popUID) %>% distinct(cohortid, date, .keep_all = T), join_by(cohortid, date))
```

## algorithm for getting new infections in long-form
```{r three-skip rule}
inc_by_three_skip <- function(pos_visit, failure_visit){
  inc_index <- c()
  end_index <- c()
  if_active_on_trt <- 0
  if (sum(pos_visit) == 0){ # if not infection, just return empty lists
    return(list(inc_index = inc_index,
                end_index = end_index,
                if_active_on_trt = if_active_on_trt))
  }
  n <- length(pos_visit)
  cur_inf <- which(pos_visit == 1)[1] # initialize first infection
  inc_index <- c(inc_index, cur_inf)
  skip <- 0
  if (cur_inf < n){
    for (i in (cur_inf+1) : n){
      if (pos_visit[i] == 0){ # no infection
        if (failure_visit[i] == 0){ # we have a skip
          skip <- skip + 1
          if (skip == 4){ # check if we reach enough skips to be cleared
            end_index <- c(end_index, i)
            cur_inf <- NULL
          }
        }
      }
      else{ # we have an infection, reset skip
        if (is.null(cur_inf)){
          cur_inf <- i
          inc_index <- c(inc_index, cur_inf)
          skip <- 0
        }
        else{
          skip <- 0
        }
      }
    }
  }
  if (skip < 4){ # active on treatment date
    end_index <- c(end_index, n)
    if_active_on_trt <- 1
  }
  return(list(inc_index = inc_index,
                end_index = end_index,
                if_active_on_trt = if_active_on_trt))
}
```

```{r main algorithm}
df_longform_inf <- data.frame(matrix(nrow = 0, ncol = 5))
colnames(df_longform_inf) <- c("cohortid", "date", "end_date", "h_popUID", "baseline")
list_cohortid <- unique(df.allvisit$cohortid)
for (id in list_cohortid){
  list_trt_date <- df.allvisit %>% filter(cohortid == id, malariacat == 3) %>% arrange(date) %>% pull(date)
  timeline_ind <- df.allvisit %>% filter(cohortid == id) %>% arrange(date) %>% pull(date)
  baseline_date <- (df.allvisit %>% filter(cohortid == id) %>% pull(enrolldate))[1] + days(60)
  broken_timeline_ind <- list() # break timeline by trt date
  timeline_ind_temp <- timeline_ind
  i <- 0
  for (trt_date in list_trt_date){
    i <- i + 1
    broken_timeline_ind[[i]] <- timeline_ind_temp[timeline_ind_temp <= trt_date]
    timeline_ind_temp <- timeline_ind_temp[timeline_ind_temp > trt_date]
  }
  if (length(timeline_ind_temp) != 0){
    broken_timeline_ind[[i+1]] <- timeline_ind_temp
  }
  list_active_clone <- c() # save active clone on the trt date of last time window
  list_active_clone_temp <- c() # save active clone on the trt date of this time window
  trt_date <- NULL # last trt date
  failure_date <- df.allvisit %>% 
    filter(cohortid == id) %>%
    filter(is.na(qpcr) | qpcr > 0 & is.na(h_popUID)) %>%
    arrange(date) %>%
    pull(date) # failure date
  for (i in 1: length(broken_timeline_ind)){
    cur_time_window <- broken_timeline_ind[[i]]
    list_clone <- unique(df.pbc %>% filter(cohortid == id, 
                                           date %in% cur_time_window) %>%
                           pull(h_popUID))
    for (clone in list_clone){
      pos_date <- df.pbc %>% filter(cohortid == id, 
                                    h_popUID == clone,
                                    date %in% cur_time_window) %>%
        arrange(date) %>% pull(date)
      if (clone %in% list_active_clone){ # remove residual
        pos_date_in_residual_window <- pos_date[pos_date <= trt_date + days(30)]
        for (d in pos_date_in_residual_window){
          if ((df.allvisit %>% filter(cohortid == id, date == d) %>% pull(parasitedensity))[1] == 0){
            pos_date <- pos_date[pos_date !=d ]
          }
        }
      }
      pos_visit <- as.numeric(cur_time_window %in% pos_date)
      failure_visit <- as.numeric(cur_time_window %in% failure_date)
      res <- inc_by_three_skip(pos_visit, failure_visit)
      inc_index <- res$inc_index
      end_index <- res$end_index
      if_active_on_trt <- res$if_active_on_trt
      if (length(inc_index) != 0){
        incident_infection_dates <- cur_time_window[inc_index]
        infection_end_dates <- cur_time_window[end_index]
        df_longform_inf <- rbind(df_longform_inf, 
                                 data.frame(cohortid = id, 
                                            date = incident_infection_dates, 
                                            end_date = infection_end_dates, 
                                            h_popUID = clone,
                                            baseline = as.numeric(i == 1 & incident_infection_dates <= baseline_date)))
      }
      if (if_active_on_trt == 1){
        list_active_clone_temp <- c(list_active_clone_temp, clone)
      }
    }
    list_active_clone <- list_active_clone_temp # update trt condition for next time window
    list_active_clone_temp <- c()
    trt_date <- cur_time_window[length(cur_time_window)]
  }
}
```

## organize into incident infection dataframe
```{r organize into final incident dataframe}
df.incident <- df.allvisit %>% select(cohortid, date, qpcr)
df.incident$incident <- 0
df.incident$COI <- 0
for (i in 1: nrow(df_longform_inf)){
  id <- df_longform_inf[i, "cohortid"]
  start_date <- df_longform_inf[i, "date"]
  end_date <- df_longform_inf[i, "end_date"]
  baseline <- df_longform_inf[i, "baseline"]
  if (baseline == 0){ # add incident
    df.incident[df.incident$cohortid == id & df.incident$date == start_date, "incident"] <- 1
  }
  df.incident[df.incident$cohortid == id & df.incident$date >= start_date & df.incident$date <= end_date, "COI"] <- 
    df.incident[df.incident$cohortid == id & df.incident$date >= start_date & df.incident$date <= end_date, "COI"] + 1 # add COI
}
# add failure
df.incident <- df.incident %>% 
  left_join(df.pbc %>% select(cohortid, date, h_popUID) %>% distinct(cohortid, date, .keep_all = T), join_by(cohortid, date)) %>% 
  mutate(incident = ifelse(is.na(qpcr)|(qpcr>0 & is.na(h_popUID)), NA, incident)) %>% 
  select(!h_popUID) %>% arrange(cohortid)
```

## Plot individual timeline
```{r dataframe preparation for plotting}
df.allvisit.plot <- df.allvisit %>%
  mutate(fill_status = case_when(
    BSdich == 1 | qPCRdich == 1  ~ 'parasite_positive',
    TRUE ~ 'parasite_negative'
  ), 
  colour_status = case_when(
    malariacat != 3 & BSdich == 1  ~ 'asymp-bloodsmear+',
    malariacat != 3 & qPCRdich == 1 ~ 'asymp-qpcr+',
    malariacat == 3 ~ 'malaria',
    TRUE ~ 'qpcr-'),
  shapeBool = ifelse(fill_status == 'parasite_negative', 1, 0)) %>%
  dplyr::select(cohortid, date, qpcr, qPCRdich, fill_status, colour_status, shapeBool, parasitedensity) %>% 
  mutate(cohortid = as.character(cohortid)) %>%
  mutate(parasiteLevel = case_when(
    qpcr > 0 & qpcr <= 10 | qpcr > 0 & parasitedensity == 0 ~ ">0 but <=10 parasites/ul OR LAMP+ microscopy negative",
    qpcr > 10 & qpcr <= 100 ~ ">10 to <=100 parasites/ul",
    qpcr > 100 & qpcr <= 1000 ~ ">100 to <=1000 parasites/ul",
    qpcr > 1000 & qpcr <= 3000 ~ ">1000 to <=3000 parasites/ul",
    qpcr > 3000 ~ ">3000 parasites/ul",
    .default = NA
  ))

df.pbc.plot <- df.pbc %>% 
  left_join(df.allvisit %>% select(!h_popUID), join_by(cohortid, date)) %>% 
  mutate(hap_qpcr = qpcr*c_AveragedFrac)

mycolors = c("parasite_positive.malaria" = "red",
             "parasite_positive.asymp-qpcr+"="royalblue", 
             "parasite_positive.asymp-bloodsmear+"="forestgreen", 
             "parasite_negative.qpcr-" = "peru",
             ">3000 parasites/ul" = "#d7191c",
             ">1000 to <=3000 parasites/ul" = "#fdae61",
             ">100 to <=1000 parasites/ul" = "#ffffbf",
             ">10 to <=100 parasites/ul" = "#abd9e9",
             ">0 but <=10 parasites/ul OR LAMP+ microscopy negative" = "#2c7bb6")
```

```{r process haplotype name and frequency}
# compute frequency
hap_list <- unique(df.pbc.plot$h_popUID)
hap_freq_list <- c()
N_clones <- nrow(df.pbc)
for (hap in hap_list){
  hap_freq_list <- c(hap_freq_list, sum(df.pbc$h_popUID == hap)/N_clones)
}
hap_freq_list <- round(hap_freq_list*100, digits = 1)

# change name
df.pbc.plot$h_popUID <- substr(df.pbc.plot$h_popUID, 8, 10)
hap_list <- substr(hap_list, 8, 10)
for (i in 1: length(hap_list)){
  hap <- hap_list[i]
  freq <- hap_freq_list[i]
  df.pbc.plot[df.pbc.plot$h_popUID == hap, "h_popUID"] <- paste0(hap, "(", freq, "%)")
}

```

```{r plot timeline}
hap.plot <- function(id, parasiteLevel = FALSE){
  age <- round(min(all.visit.border %>% filter(cohortid == id) %>% pull(ageyrs)),digits = 1)
  age.lab <- c(paste0(id, " (",age,"yrs)"))
  names(age.lab) <- c(id)
  haplodrop <- ggplot(data = df.pbc.plot %>% filter(cohortid == id)) + #%>% filter(infection_events > 2)) +
  
    # haplotype squares
    geom_point(shape = 22,
             aes(x = date, y = factor(h_popUID), size = log10(hap_qpcr), fill = factor(h_popUID))) +
  
    # timeline points
    geom_point(data = df.allvisit.plot %>% filter(cohortid == id), size = 3, alpha = 0.4, aes(
      x = date,
      y = ' visit',
      colour = as.factor(interaction(fill_status, colour_status)))) +
    
    # incident infection
    geom_point(data = df.incident %>% filter(cohortid == id, incident == 1),
               size = 3, shape = 4, aes(x = date, y = " incident")) +
    
    # theme and facets
    facet_wrap(~cohortid, scale = 'free_y',labeller = labeller(cohortid = age.lab)) +
    theme_classic() +
    guides(fill= "none",
           colour = guide_legend(title = 'Visit Type'),
           size = guide_legend(title = 'qPCR (log10)'),
           shape= "none"
    ) +
    scale_colour_manual(values = mycolors) +
    # scale_shape_manual(values = c(16, 21)) +
    scale_y_discrete(expand= c(0,1), limits = rev) +
    theme(aspect.ratio = 0.3,
          axis.text.y =  element_text(angle = 30)) +
    labs(x = 'Date', y = 'Haplotype Population', title = 'Haplotype Timelines')
  if (parasiteLevel){
    nLevel <- length(unique(df.allvisit.plot %>% 
                             filter(cohortid == id, !is.na(parasiteLevel)) %>%
                              pull(parasiteLevel)))
    nVisitType <- length(unique(df.allvisit.plot %>%
                                  filter(cohortid == id) %>%
                                  mutate(visitType = as.factor(interaction(fill_status, colour_status))) %>%
                                  pull(visitType)))
    haplodrop <- haplodrop + geom_point(data = df.allvisit.plot %>% 
                             filter(cohortid == id, !is.na(parasiteLevel)), 
                           aes(x = date, 
                               y = " density category", 
                               color = as.factor(parasiteLevel)),
                           size = 3,
                           shape = 15,
                           alpha = 0.4) +
      guides(color = guide_legend(override.aes=list(shape = c(rep(15, nLevel), rep(19, nVisitType)))))
  }
  return(haplodrop)
}
```

```{r save plot}
for (id in unique(df.allvisit$cohortid)){
  n_hap <- length(unique(df.pbc.plot %>% filter(cohortid == id) %>% pull(h_popUID)))
  ggsave(filename = paste0("incident_timeline/cohortid_", id, ".png"), plot = gridExtra::grid.arrange(egg::set_panel_size(p=hap.plot(id, T), width=unit(15, "cm"), height=unit(5 + n_hap * 0.5, "cm"))), 
         width = 10, height = 10)
}
```
